
languageCode = "ar"
title = "قناة TechTouch"
defaultContentLanguage = "ar"

# إعدادات ترقيم الصفحات
paginate = 10
paginatePath = "page"

[params]
  description = "اضغط على أي قسم للانتقال إليه مباشرة"
  author = "TechTouch"
  contentType = "text/html; charset=utf-8"
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

# إعدادات الروابط الدائمة
[permalinks]
  posts = "/posts/:slug/"

[menu]
  [[menu.main]]
    name = "الرئيسية"
    url = "/"
    weight = 1





uglyURLs = true
disablePathToLower = true



[languages]
  [languages.ar]
    contentDir = "content"
    languageName = "العربية"
    weight = 1
    rtl = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]

[mediaTypes]
  [mediaTypes."application/json"]
    suffixes = ["json"]

[outputFormats]
  [outputFormats.JSON]
    mediaType = "application/json"
    isPlainText = true
    notAlternative = true



