backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "المنشورات"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string", required: true}
      - {label: "التاريخ", name: "date", widget: "datetime", required: true}
      - {label: "المسودة", name: "draft", widget: "boolean", default: false, required: true}
      - {label: "الفئة", name: "category", widget: "select", options: ["movies", "sports", "video-design", "misc"], required: true}
      - {label: "الوصف", name: "description", widget: "text", required: true}
      - {label: "الصورة (اختيارية)", name: "image", widget: "image", required: false}
      - {label: "الملف (اختياري)", name: "file", widget: "file", required: false}
      - {label: "المحتوى", name: "body", widget: "markdown", required: false}

