backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "المنشورات"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string"}
      - {label: "التاريخ", name: "date", widget: "datetime"}
      - {label: "المسودة", name: "draft", widget: "boolean", default: false}
      - {label: "الفئة", name: "category", widget: "select", options: ["movies", "sports", "video-design", "misc"]}
      - {label: "الوصف", name: "description", widget: "text"}
      - {label: "الرابط", name: "link", widget: "string"}
      - {label: "المحتوى", name: "body", widget: "markdown"}
      - {label: "ملف التحميل", name: "download_file", widget: "file", allow_multiple: false}

