backend:
  name: git-gateway
  branch: main
  auth:
    provider: auth0
    client_id: 7R63Su5lCVygV9dJiWPLDG0fCmMu0NWF
    domain: dev-nd1cktzyoebormj8.us.auth0.com

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "المنشورات"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "العنوان", name: "title", widget: "string", required: false}
      - {label: "التاريخ", name: "date", widget: "datetime", required: false}
      - {label: "الفئة", name: "category", widget: "select", options: ["أفلام", "رياضة", "تصميم الفيديو", "متنوع"], required: false}
      - {label: "رابط التحميل", name: "download_link", widget: "string", required: false}
      - {label: "الملخص", name: "summary", widget: "text", required: false}
      - {label: "المحتوى", name: "body", widget: "markdown", required: false}



      - {label: "الملف المرفق", name: "file_upload", widget: "file", required: false}


